### PR TITLE
Choose Folder Option

### PR DESCRIPTION
**Pull request by nielsdebruin**
This PR adds the ability to select folders.

**Usage**

The user can create a new folder chooser using either:

- `new MaterialFilePicker().withChooseFolderMode(true)`

- `intent.putExtra(FilePickerActivity.ARG_CHOOSE_FOLDER_MODE, true);`

When _choose folder mode_ is enabled a floating action button will pop up. Pressing the button will select the currently opened folder.

image

### CODE REVIEW

**Comment by Angelk90** [comment]
@nielsdebruin : are there any news?

**Comment by prscX** [comment]
Hi, Can someone please review and merge this PR. It will enable users to select document.

Thanks
Pranav

**Comment by Angelk90** [comment]
@lukaville, @dimorinny: There are news?

**Comment by crutchcorn** [comment]
Is there any update on this? I'm hoping to build a React native app that builds on top of this

**Pull request closed without merging**
